### ISSUE TITLE
Issue with "Multiplicación Exponencial" Research on Wraiths

### ISSUE THREAD

**Issue by moonberserker** [KevinGuancheDarias/owge#109]
The "Multiplicación Exponencial" Research states in it's description that it adds 35% to the production of biomatter but it augments food production instead.

**Comment by KevinGuancheDarias** [comment]
Hello @moonberserker, thank you for your report, I will investigate this issue :smiley:

**Comment by KevinGuancheDarias** [comment]
Closing, not an OWGE issue, it's a SGT configuration problem
