### ISSUE TITLE
If you activate temporary special units on any planet, they appear on the home planet. 

### ISSUE THREAD

**Issue by Dranot** [KevinGuancheDarias/owge#470]
Is it possible that if you activate it on a planet other than the home planet, they will appear on that planet?

**Comment by KevinGuancheDarias** [comment]
This will be done maybe in the future, is a hard task due to how the temporary units work under the hood

**Comment by KevinGuancheDarias** [comment]
This can be done if the frontend sends the "selectedPlayer" in each request, and make it available in the context
